services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - "~/files:/srv"
      - "~/app/filebrowser/config:/config"
      - "~/app/filebrowser/database:/database"
      - "~/app/filebrowser/branding:/branding"
    environment:
      - FB_TOKEN_EXPIRATION_TIME=500h

networks:
  homelab:
    external: true
