services:
  server:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - homelab
    volumes:
      - ~/files:/srv
      - ~/filebrowser/config:/config
      - ~/filebrowser/database:/database

networks:
  homelab:
    external: true
